### PR TITLE
chore: update nodejs version

### PR DESCRIPTION
**Pull request by omerlh**
fix for #590

### CODE REVIEW

**Review by shaikatz — APPROVED** [review]
LGTM

**Comment by wimo7083** [comment]
Ty for doing this.

**Comment by shaikatz** [comment]
@omerlh Can you merge that?

**Comment by omerlh** [comment]
Hey @wimo7083 can you please try building the new docker image? I did not have time to test it

**Comment by wimo7083** [comment]
Sorry, didn't notice this until now.

Build:
```bash
$ ~/kamus/cli$ git branch
* chore/update-cli-nodejs-version

$ docker build -t kamus:test-tls .
...
```

Encrypt:

```bash
$ sudo docker run -it --rm kamus:test-tls encrypt --secret "thing" --kamus-url "https://kamus.example.com" --service-account kamus-default --namespace kamus
[info  kamus-cli]: Encryption started...
[info  kamus-cli]: service account: kamus-default
[info  kamus-cli]: namespace: kamus
[warn  kamus-cli]: Auth options were not provided, will try to encrypt without authentication to kamus
(node:1) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
[info  kamus-cli]: Successfully encrypted data to kamus-default service account in kamus namespace
[info  kamus-cli]: Encrypted data:
$ENCRYPTED_SECRET
```
Decrypt

```bash
kubectl port-forward svc/kamus-decryptor --namespace kamus 8099:80

$ cat secret-data.json
{"data": "$ENCRYPTED_SECRET"}

curl localhost:8099/api/v1/decrypt \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $(
    kubectl get secret \
      --namespace kamus \
      --output jsonpath='{.items[?(@.metadata.annotations.kubernetes\.io/service-account\.name == "default")].data.token}' |
      base64 -d
    )" \
  -d @secret-data.json
```

**Comment by shaikatz** [comment]
Looks good! I'll merge it, thanks @wimo7083 and @omerlh

**Pull request merged**
