### PR TITLE
Infinite watching in the CRD controller

### LINKED ISSUE #598: How to mitigate kamus-controller restarts impacting dependent systems?
**Describe the bug**
This is less of a bug, and more asking what should be done to get around this issue which causes operational troubles from the scheduled kamus-controller hourly restart.

I was [asked](https://github.com/Soluto/kamus/issues/517#issuecomment-724135627) to make a new issue regarding this.

I understand kamus-controller [restarting every 60 minutes is normal](https://github.com/Soluto/kamus/issues/589#issuecomment-695922816). 

I'm not sure how to make dependent systems behave properly when this scheduled "downtime" occurs.
- fluxcd
- CI/CD
- monitoring 
- kamus-cli

I've seen kamus-controller cause problems when a new HelmRelease is pushed out.

An example of a dependent system having trouble during these restarts
```bash
{
  "caller": "loop.go:108",
  "component": "sync-loop",
  "err": "collating resources in cluster for sync: conversion webhook for soluto.com/v1alpha2, Kind=KamusSecret failed: Post https://kamus-controller.kamus.svc:443/api/v1/conversion-webhook?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)",
  "ts": "2020-11-04T00:04:18.249326875Z"
}
```

I've seen two types of failure modes:
kamus-init-containers

1. New/ modified HR- flux notices and updates HR
2. Helm-operator notices- and tries to updates using the kamus-init-container
3. Endpoint fails which gives the log above, this cause the CM or whatever you are creating with kamus-init-container to fail
4. Since Kamus couldn't secret- the helmrelease fails

KamusSecret failure:
1. New/ modified HR- flux notices and updates HR and the KamusSecret
2. kamus-controller restarts which causes a 1-3 minute delay on performing conversion.
3. Something in the HR is dependent upon the corresponding output "secret" object- this delay causes an ordered dependency update failure.
4. The dependent resource isn't smart enough/ aware enough to retry and the helm hooks aren't configured properly to handle this.

This is a mixture of 3 problems (flux, kamus, helm), so I don't fault any one of them. My only thought is to add more replicas of the kamus-controller, but all I'm doing is reducing the failure rate (if this is even recommended), I'm not even sure if a poddisruptionbudget with 2 replicas would matter if the pod itself is causing the restart.

**Versions used**
I can include my versions if desired, as this is a question on how to get around the design of kamus-controller restarts.

### PR DESCRIPTION
**Pull request by shaikatz**
Closes #598 
There is no real reason for the 60 minutes timeout.
The kubernetes API is capable of receiving watch requests with infinite timeout - as soon as Kubernetes will decide to drop it, there is internal watcherLoop in the csharp client, that will handle the re-watching operation.

### CODE REVIEW

**Review by omerlh — COMMENTED** [review]
Wonder how we can test that - can we have healthcheck that ensure the controller is still connected?

**Comment by shaikatz** [comment]
If the watch will complete we have a code that closes the process, isn't that enough?

**Comment by omerlh** [comment]
I know things like external secrets sometimes loosing the watch, but think they still has it - probably k8s bug. This is why I suggested adding healthcheck

**Comment by shaikatz** [comment]
This is the reason csharp client has the watcher loop (https://github.com/kubernetes-client/csharp/pull/184) it should handle that.
It will be very hacky to make the isAlive checking that we actually picking items, since the watcher is based on objects being created.

**Comment by omerlh** [comment]
Sounds good, maybe let's add monitoring for the last time we got an event?

**Comment by shaikatz** [comment]
That a great idea, please check my last commit.

**Review by omerlh — APPROVED** [review]

**Comment by shaikatz** [comment]
New PR created a more up to date with recent version

**Pull request closed without merging**
